# Generated by Django 4.1 on 2022-08-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=40)),
                ('tashabbuskor', models.CharField(max_length=100, verbose_name='loyiha tashabbuskori')),
                ('maqsad', models.CharField(max_length=200, verbose_name='loyiha maqsadi')),
                ('qiymati', models.BigIntegerField(default=0, verbose_name='loyiha qiymati (mln. sumda)')),
                ('mablag', models.BigIntegerField(default=0, verbose_name="Uz mablag'lari")),
                ('kredit', models.BigIntegerField(default=0, verbose_name='Bank kreditlari')),
                ('valyuta', models.BigIntegerField(default=0, verbose_name='Milliy valyuta')),
                ('valyuta_xorij', models.BigIntegerField(default=0, verbose_name='Xorijiy valyuta')),
                ('investitsiya', models.BigIntegerField(default=0, verbose_name='Xorijiy invastitsiya')),
                ('ishchi_urin', models.IntegerField(default=0, verbose_name="Ishchi O'rin")),
                ('bank_kredeti', models.BigIntegerField(default=0, verbose_name='Haqiqatda ajratilgan bank kreditlari')),
                ('muddat', models.DateField(verbose_name='Loyiha ishga tushish muddati')),
                ('izoh', models.TextField()),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viloyat')),
            ],
        ),
    ]
