# Generated by Django 4.1 on 2022-08-04 07:56

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loyiha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyiha',
            name='status',
            field=model_utils.fields.StatusField(choices=[('ishga_tushmagan', 'Ishga Tushmagan'), ('ishga_tushgan', 'Ishga Tushgan')], default='ishga_tushmagan', max_length=100, no_check_for_status=True),
        ),
    ]
