# Generated by Django 4.1 on 2022-08-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_status_alter_loyiha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyiha',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status', verbose_name='Loyiha holati'),
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='viloyat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.viloyat'),
        ),
    ]
